[DEFAULT]
# 邮件服务器配置
mail_server = smtp-mail.outlook.com
mail_port = 587
mail_use_tls = True
mail_username = example@outlook.com
mail_password = password
mail_default_sender = example@outlook.com

# DeepSeek API配置
deepseek_api_key = sk-xxxxxxxxxxxxxx
# 系统配置
daily_practice_time = 07:00
#Remember: don't share your API key with anyone!