[DEFAULT]
# 邮件服务器配置
mail_server = smtp.office365.com
mail_port = 587
mail_use_tls = True
mail_username = carywang666@outlook.com
mail_password = poke2013
mail_default_sender = carywang666@outlook.com

# DeepSeek API配置
deepseek_api_key = sk-8e5cb00da23549a6bdac8e49af6529a8
# 系统配置
daily_practice_time = 07:00